### ISSUE TITLE
直接支持5700xt么？

### ISSUE THREAD

**Issue by JerryCol** [TheStupidNoob/AMDRyzen-Hackintosh-Opencore#3]
2年前玩过，现在忘完了=。=

**Comment by No06** [comment]
支持，具体可以看README

**Comment by JerryCol** [comment]
> 支持，具体可以看README

那么快就回了。。。那我ssd到了，我早点弄好=。=

pcbeta关球了，烦死了。。。我之前有分享我自己的opencore去bbs，2600+b450m mortar+5700xt

**Comment by JerryCol** [comment]
> 支持，具体可以看README

对了，我用properties看了下，好像你没加5700或者a卡的驱动也。。还有8111网卡，也是。。。
是现在opencore已经不需要写驱动了么。。。

**Comment by No06** [comment]
> 

一般显卡不需要额外驱动，网卡是用kext

**Comment by JerryCol** [comment]
> > 
> 
> 一般显卡不需要额外驱动，网卡是用kext

哦哦，以前pcbeta有位巨佬研究的5700加代码写入后，macos直接认成w5700什么的，性能提升不少。。我自己注入进去了😅

**Comment by No06** [comment]
> > > 
> > 
> > 
> > 一般显卡不需要额外驱动，网卡是用kext
> 
> 哦哦，以前pcbeta有位巨佬研究的5700加代码写入后，macos直接认成w5700什么的，性能提升不少。。我自己注入进去了😅

还有这种操作，学习了
