### ISSUE TITLE
为毛我进入usb启动 （你第二张图）一共四个图标我就两个图标，都是windows，主板是被50

### ISSUE THREAD

**Issue by HD12138** [TheStupidNoob/AMDRyzen-Hackintosh-Opencore#5]

**Comment by HD12138** [comment]
![image](https://user-images.githubusercontent.com/95847253/225927152-4ed1bfb4-fd55-4e45-9d9e-0fd4e4e91825.png)

**Comment by No06** [comment]
你有几个系统就有几个图标，并不是固定的，这张图只想展示引导主题界面

**Comment by HD12138** [comment]
大佬，可以支持什么支持什么系统，是不是
![image](https://user-images.githubusercontent.com/95847253/225937598-cdf32eb7-03ea-444c-bb08-9d53b6b6a27e.png)

**Comment by HD12138** [comment]
下面下载的  还是去下载镜像来？

**Comment by No06** [comment]
11或以上应该都没问题，你这个脚本我没用过不清楚，一般是下载.dmg镜像

**Comment by HD12138** [comment]
就是说先安装好苹果。然后再替换到你的文件是吗？

**Comment by No06** [comment]
没有我这个EFI引导你装不了
所以应该先写入镜像到u盘里，然后再添加EFI到硬盘，就可以进系统安装了

**Comment by No06** [comment]
具体步骤的话不看视频教程是很难做的，建议先去做足功课
