### ISSUE TITLE
B450M MORTAR TITANIUM这个板子能用吗

### ISSUE THREAD

**Issue by 1205129045x** [TheStupidNoob/AMDRyzen-Hackintosh-Opencore#6]
叫b450m迫击炮钛金版，纯白色主板
![image](https://github.com/No06/B450M-Mortar-OpenCore/assets/50540240/9a208936-d2c5-451a-80eb-51d5d9202cf5)

**Comment by No06** [comment]
可以的，只要是迫击炮，或者是微星的基本上都可以用，我自己现在是B450i但依旧完美兼容

**Comment by 1205129045x** [comment]
你是华硕的b450i吗，也可以用这个efi啊，我现在就是睡眠经常出问题，睡眠得按开机键才能唤醒，有时候还唤醒不了，只能强制关机再开机。

**Comment by No06** [comment]
微星的b450i，睡眠和休眠不一样，睡眠就是只能按开机键启动，休眠才可以动鼠标键盘唤醒，睡眠的话好像是有点不稳定，等14正式版出了再修修看了

**Comment by Kaijun** [comment]
@No06 请问睡眠正常吗，我 B450m Mortar + R5-5600G + RX580 有时候能睡眠，有时候无法进入。

都无法正常唤醒（唤醒显示器不亮）。不插 usb 设备，只插键鼠，都无法正常睡眠和唤醒

自己做了 USBMap 还是没有效果，不知道大佬有没有经验

**Comment by No06** [comment]
> @No06 请问睡眠正常吗，我 B450m Mortar + R5-5600G + RX580 有时候能睡眠，有时候无法进入。
> 
> 都无法正常唤醒（唤醒显示器不亮）。不插 usb 设备，只插键鼠，都无法正常睡眠和唤醒
> 
> 自己做了 USBMap 还是没有效果，不知道大佬有没有经验

我这边的情况也是有时候可以有时候不行，等14 RC了到时候更新会试试去解决一下

**Comment by 1205129045x** [comment]
> 微星的b450i，睡眠和休眠不一样，睡眠就是只能按开机键启动，休眠才可以动鼠标键盘唤醒，睡眠的话好像是有点不稳定，等14正式版出了再修修看了

主板里面开那个usb s3/s4唤醒，睡眠的时候可以键盘唤醒

**Comment by Kaijun** [comment]
> > @No06 请问睡眠正常吗，我 B450m Mortar + R5-5600G + RX580 有时候能睡眠，有时候无法进入。
> > 都无法正常唤醒（唤醒显示器不亮）。不插 usb 设备，只插键鼠，都无法正常睡眠和唤醒
> > 自己做了 USBMap 还是没有效果，不知道大佬有没有经验
> 
> 我这边的情况也是有时候可以有时候不行，等14 RC了到时候更新会试试去解决一下

我看到 https://github.com/erhuoL/hackintosh-B450m-mortar-max 这个项目内有关于 bios 的设置

> 睡眠和唤醒：关闭bios里面的串行端口即可支持睡眠唤醒

我试下是否能解决

**Comment by Kaijun** [comment]
以及这位大佬的[仓库](https://github.com/VanXNF/Hackintosh-Ryzen-3500X-MSI-B450M-Mortar-MAX) 的[远景帖子](https://bbs.pcbeta.com/viewthread-1866498-1-1.html)

也有提到关闭串行端口，我晚点回去试一下

**Comment by No06** [comment]
期待结果

**Comment by Kaijun** [comment]
@No06 最终发现应该是 5600g 自带核显导致的

加上 -wegnoigpu 屏蔽 IGPU 就解决了

感谢！
